Repository googleapis/java-secretmanager, pull requests merged in 2020-06, with the labels that each got.

#141 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#127 docs: regenerate docs from protos
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretPayload.java
  proto-google-cloud-secretmanager-v1/src/main/proto/google/cloud/secretmanager/v1/resources.proto
  proto-google-cloud-secretmanager-v1/src/main/proto/google/cloud/secretmanager/v1/service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#144 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#143 chore: regenerate with updated protoc
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/AccessSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/AccessSecretVersionResponse.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/AddSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/CreateSecretRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DeleteSecretRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DestroySecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DisableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/EnableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/GetSecretRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/GetSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ListSecretVersionsRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ListSecretVersionsResponse.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ListSecretsRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ListSecretsResponse.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/Replication.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/Secret.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretPayload.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretVersion.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/UpdateSecretRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/AccessSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/AccessSecretVersionResponse.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/AddSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/CreateSecretRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/DeleteSecretRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/DestroySecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/DisableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/EnableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/GetSecretRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/GetSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/ListSecretVersionsRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/ListSecretVersionsResponse.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/ListSecretsRequest.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/ListSecretsResponse.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/Replication.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/Secret.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/SecretPayload.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/SecretVersion.java
  proto-google-cloud-secretmanager-v1beta1/src/main/java/com/google/cloud/secretmanager/v1beta1/UpdateSecretRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 samples: use exclude tag for install_with_bom snippet
  samples/snippets/pom.xml
Labels: cla: yes

#155 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#156 chore: regenerate README and fix whitespace
  README.md
  samples/snippets/pom.xml
  synth.metadata
Labels: cla: yes

#159 fix: migrate secretmanager to grpc_service_config
  google-cloud-secretmanager/src/main/java/com/google/cloud/secretmanager/v1/stub/SecretManagerServiceStubSettings.java
  google-cloud-secretmanager/src/main/java/com/google/cloud/secretmanager/v1beta1/stub/SecretManagerServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#161 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#167 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#168 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-secretmanager/pom.xml
  grpc-google-cloud-secretmanager-v1/pom.xml
  grpc-google-cloud-secretmanager-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-secretmanager-v1/pom.xml
  proto-google-cloud-secretmanager-v1beta1/pom.xml
Labels: cla: yes

#180 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
