Repository googleapis/java-secretmanager, pull requests merged in 2020-09, with the labels that each got.

#213 docs: remote redundant comments
  proto-google-cloud-secretmanager-v1/src/main/proto/google/cloud/secretmanager/v1/service.proto
  proto-google-cloud-secretmanager-v1beta1/src/main/proto/google/cloud/secrets/v1beta1/service.proto
  synth.metadata
Labels: api: secretmanager, cla: yes, context: full

#209 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: secretmanager, cla: yes, context: full

#221 chore: regenerate README
  README.md
  synth.metadata
Labels: api: secretmanager, cla: yes, context: none

#223 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#234 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#233 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: secretmanager, automerge, cla: yes

#241 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#243 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
