Repository googleapis/java-secretmanager, pull requests merged in 2021-05, with the labels that each got.

#466 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: none

#467 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: secretmanager, automerge, cla: yes

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes

#476 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes

#477 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#482 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes

#483 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#485 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#488 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#481 feat: Etags in Secret Manager
  google-cloud-secretmanager/src/main/java/com/google/cloud/secretmanager/v1/SecretManagerServiceClient.java
  google-cloud-secretmanager/src/test/java/com/google/cloud/secretmanager/v1/SecretManagerServiceClientTest.java
  grpc-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretManagerServiceGrpc.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/AccessSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/AccessSecretVersionRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DeleteSecretRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DeleteSecretRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DestroySecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DestroySecretVersionRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DisableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/DisableSecretVersionRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/EnableSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/EnableSecretVersionRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/GetSecretVersionRequest.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/GetSecretVersionRequestOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ResourcesProto.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/Rotation.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/RotationOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/Secret.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretVersion.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/SecretVersionOrBuilder.java
  proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/ServiceProto.java
  proto-google-cloud-secretmanager-v1/src/main/proto/google/cloud/secretmanager/v1/resources.proto
  proto-google-cloud-secretmanager-v1/src/main/proto/google/cloud/secretmanager/v1/service.proto
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#493 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: secretmanager, automerge, cla: yes
